kitsune/kbforums/urls.py
from django.conf.urls import patterns, url
from django.contrib.contenttypes.models import ContentType

from kitsune.kbforums.feeds import ThreadsFeed, PostsFeed
from kitsune.kbforums.models import Post
from kitsune.flagit import views as flagit_views


# These patterns inherit from /document/discuss
urlpatterns = patterns(
    'kitsune.kbforums.views',
    url(r'^$', 'threads', name='wiki.discuss.threads'),
    url(r'^/feed', ThreadsFeed(), name='wiki.discuss.threads.feed'),
    url(r'^/new', 'new_thread', name='wiki.discuss.new_thread'),
    url(r'^/watch', 'watch_forum', name='wiki.discuss.watch_forum'),
    url(r'^/post-preview-async$', 'post_preview_async',
        name='wiki.discuss.post_preview_async'),
    url(r'^/(?P<thread_id>\d+)$', 'posts', name='wiki.discuss.posts'),
    url(r'^/(?P<thread_id>\d+)/feed$', PostsFeed(),
        name='wiki.discuss.posts.feed'),
    url(r'^/(?P<thread_id>\d+)/watch$', 'watch_thread',
        name='wiki.discuss.watch_thread'),
    url(r'^/(?P<thread_id>\d+)/reply$', 'reply', name='wiki.discuss.reply'),
    url(r'^/(?P<thread_id>\d+)/sticky$', 'sticky_thread',
        name='wiki.discuss.sticky_thread'),
    url(r'^/(?P<thread_id>\d+)/lock$', 'lock_thread',
        name='wiki.discuss.lock_thread'),
    url(r'^/(?P<thread_id>\d+)/edit$', 'edit_thread',
        name='wiki.discuss.edit_thread'),
    url(r'^/(?P<thread_id>\d+)/delete$', 'delete_thread',
        name='wiki.discuss.delete_thread'),
    url(r'^/(?P<thread_id>\d+)/(?P<post_id>\d+)/edit', 'edit_post',
        name='wiki.discuss.edit_post'),
    url(r'^/(?P<thread_id>\d+)/(?P<post_id>\d+)/delete', 'delete_post',
        name='wiki.discuss.delete_post'),
    # Flag discussion posts
    url(r'^/(?P<object_id>\d+)/flag$', flagit_views.flag,
        {'content_type': ContentType.objects.get_for_model(Post).id},
        name='wiki.discuss.flag_post'),
)

kitsune/urls.py
from django.conf.urls import include, patterns, url
from django.conf import settings
from django.views.i18n import javascript_catalog
from django.views.decorators.cache import cache_page
from django.views.generic.base import RedirectView

import authority
import badger
from waffle.views import wafflejs


# Note: This must come before importing admin because it patches the
# admin.
from kitsune.sumo.monkeypatch import patch
patch()

from django.contrib import admin
admin.autodiscover()

authority.autodiscover()
badger.autodiscover()


urlpatterns = patterns(
    '',
    (r'^search', include('kitsune.search.urls')),
    (r'^forums', include('kitsune.forums.urls')),
    (r'^questions', include('kitsune.questions.urls')),
    (r'^flagged', include('kitsune.flagit.urls')),
    (r'^upload', include('kitsune.upload.urls')),
    (r'^kb', include('kitsune.wiki.urls')),
    (r'^gallery', include('kitsune.gallery.urls')),
    (r'^army-of-awesome', include('kitsune.customercare.urls')),
    (r'^chat', RedirectView.as_view(url='questions/new')),
    (r'^messages', include('kitsune.messages.urls')),
    (r'^1', include('kitsune.inproduct.urls')),
    (r'^postcrash', include('kitsune.postcrash.urls')),
    (r'^groups', include('kitsune.groups.urls')),
    (r'^kpi/', include('kitsune.kpi.urls')),
    (r'^products', include('kitsune.products.urls')),
    (r'^announcements', include('kitsune.announcements.urls')),
    (r'^community', include('kitsune.community.urls')),
    (r'^badges/', include('kitsune.kbadge.urls')),

    # Kitsune admin (not Django admin).
    (r'^admin/', include(admin.site.urls)),

    # Javascript translations.
    url(r'^jsi18n/.*$', cache_page(60 * 60 * 24 * 365)(javascript_catalog),
        {'domain': 'javascript', 'packages': ['kitsune']}, name='jsi18n'),
    # Yaocho translations. These don't need cached because Yaocho downloads
    # them in a build step, not on the client.
    url(r'^jsi18n-yaocho/.*$', javascript_catalog,
        {'domain': 'yaocho', 'packages': ['kitsune']}, name='jsi18n-yaocho'),
    # JavaScript Waffle.
    url(r'^wafflejs$', wafflejs, name='wafflejs'),

    (r'^', include('kitsune.dashboards.urls')),
    (r'^', include('kitsune.landings.urls')),
    (r'^', include('kitsune.kpi.urls_api')),
    (r'^', include('kitsune.motidings.urls')),

    # Users
    ('', include('kitsune.users.urls')),

    # Services and sundry.
    (r'', include('kitsune.sumo.urls')),

    # v1 APIs
    (r'^api/1/kb/', include('kitsune.wiki.urls_api')),
    (r'^api/1/products/', include('kitsune.products.urls_api')),
    (r'^api/1/customercare/', include('kitsune.customercare.urls_api')),
    (r'^api/1/gallery/', include('kitsune.gallery.urls_api')),
    (r'^api/1/users/', include('kitsune.users.urls_api')),

    # v2 APIs
    (r'^api/2/', include('kitsune.notifications.urls_api')),
    (r'^api/2/', include('kitsune.questions.urls_api')),
    (r'^api/2/', include('kitsune.search.urls_api')),
    (r'^api/2/', include('kitsune.community.urls_api')),

    # These API urls include both v1 and v2 urls.
    (r'^api/', include('kitsune.users.urls_api')),
)

# Handle 404 and 500 errors
handler404 = 'kitsune.sumo.views.handle404'
handler500 = 'kitsune.sumo.views.handle500'

if settings.DEBUG:
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns(
        '',
        (r'^%s/(?P<path>.*)$' % media_url, 'kitsune.sumo.views.serve_cors',
         {'document_root': settings.MEDIA_ROOT}),
    )

kitsune/kbforums/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models

from tidings.models import NotificationsMixin

from kitsune import kbforums
from kitsune.sumo.helpers import urlparams, wiki_to_html
from kitsune.sumo.models import ModelBase
from kitsune.sumo.urlresolvers import reverse
from kitsune.wiki.models import Document


def _last_post_from(posts, exclude_post=None):
    """Return the most recent post in the given set, excluding the given post.

    If there are none, return None.

    """
    if exclude_post:
        posts = posts.exclude(id=exclude_post.id)
    posts = posts.order_by('-created')
    try:
        return posts[0]
    except IndexError:
        return None


class ThreadLockedError(Exception):
    """Trying to create a post in a locked thread."""


class Thread(NotificationsMixin, ModelBase):
    title = models.CharField(max_length=255)
    document = models.ForeignKey(Document)
    created = models.DateTimeField(default=datetime.datetime.now,
                                   db_index=True)
    creator = models.ForeignKey(User, related_name='wiki_thread_set')
    last_post = models.ForeignKey('Post', related_name='last_post_in',
                                  null=True)
    replies = models.IntegerField(default=0)
    is_locked = models.BooleanField(default=False)
    is_sticky = models.BooleanField(default=False, db_index=True)

    class Meta:
        ordering = ['-is_sticky', '-last_post__created']
        permissions = (
            ('lock_thread', 'Can lock KB threads'),
            ('sticky_thread', 'Can sticky KB threads'),
        )

    @property
    def last_page(self):
        """Returns the page number for the last post."""
        return self.replies / kbforums.POSTS_PER_PAGE + 1

    def __unicode__(self):
        return self.title

    def new_post(self, creator, content):
        """Create a new post, if the thread is unlocked."""
        if self.is_locked:
            raise ThreadLockedError

        return self.post_set.create(creator=creator, content=content)

    def get_absolute_url(self):
        return reverse('wiki.discuss.posts',
                       locale=self.document.locale,
                       kwargs={'document_slug': self.document.slug,
                               'thread_id': self.id})

    def update_last_post(self, exclude_post=None):
        """Set my last post to the newest, excluding the given post."""
        last = _last_post_from(self.post_set, exclude_post=exclude_post)
        self.last_post = last
        # If self.last_post is None, and this was called from Post.delete,
        # then Post.delete will erase the thread, as well.


class Post(ModelBase):
    thread = models.ForeignKey(Thread)
    content = models.TextField()
    creator = models.ForeignKey(User, related_name='wiki_post_set')
    created = models.DateTimeField(default=datetime.datetime.now,
                                   db_index=True)
    updated = models.DateTimeField(default=datetime.datetime.now,
                                   db_index=True)
    updated_by = models.ForeignKey(User,
                                   related_name='wiki_post_last_updated_by',
                                   null=True)

    class Meta:
        ordering = ['created']

    def __unicode__(self):
        return self.content[:50]

    def save(self, *args, **kwargs):
        """
        Override save method to update parent thread info and take care of
        created and updated.
        """
        new = self.id is None
        now = datetime.datetime.now()

        if new:
            self.created = now
        self.updated = now

        super(Post, self).save(*args, **kwargs)

        if new:
            self.thread.replies = self.thread.post_set.count() - 1
            self.thread.last_post = self
            self.thread.save()

    def delete(self, *args, **kwargs):
        """Override delete method to update parent thread info."""
        thread = Thread.objects.get(pk=self.thread.id)
        if thread.last_post_id and thread.last_post_id == self.id:
            thread.update_last_post(exclude_post=self)
        thread.replies = thread.post_set.count() - 2
        thread.save()

        super(Post, self).delete(*args, **kwargs)
        # If I was the last post in the thread, delete the thread.
        if thread.last_post is None:
            thread.delete()

    @property
    def page(self):
        """Get the page of the thread on which this post is found."""
        t = self.thread
        earlier = t.post_set.filter(created__lte=self.created).count() - 1
        if earlier < 1:
            return 1
        return earlier / kbforums.POSTS_PER_PAGE + 1

    def get_absolute_url(self):
        query = {}
        if self.page > 1:
            query['page'] = self.page

        url_ = reverse('wiki.discuss.posts',
                       locale=self.thread.document.locale,
                       kwargs={'document_slug': self.thread.document.slug,
                               'thread_id': self.thread.id})
        return urlparams(url_, hash='post-%s' % self.id, **query)

    @property
    def content_parsed(self):
        return wiki_to_html(self.content)

kitsune/kbforums/forms.py
from django import forms

from tower import ugettext_lazy as _lazy

from kitsune.kbforums.models import Thread, Post
from kitsune.sumo.form_fields import StrippedCharField


MSG_TITLE_REQUIRED = _lazy(u'Please provide a title.')
MSG_TITLE_SHORT = _lazy(u'Your title is too short (%(show_value)s '
                        u'characters). It must be at least %(limit_value)s '
                        u'characters.')
MSG_TITLE_LONG = _lazy(u'Please keep the length of your title to '
                       u'%(limit_value)s characters or less. It is '
                       u'currently %(show_value)s characters.')
MSG_CONTENT_REQUIRED = _lazy(u'Please provide a message.')
MSG_CONTENT_SHORT = _lazy(u'Your message is too short (%(show_value)s '
                          u'characters). It must be at least %(limit_value)s '
                          u'characters.')
MSG_CONTENT_LONG = _lazy(u'Please keep the length of your message to '
                         u'%(limit_value)s characters or less. It is '
                         u'currently %(show_value)s characters.')


class ReplyForm(forms.ModelForm):
    """Reply form for forum threads."""
    content = StrippedCharField(
        label=_lazy(u'Content:'),
        min_length=5,
        max_length=10000,
        widget=forms.Textarea(attrs={'rows': 10, 'cols': 80}),
        error_messages={'required': MSG_CONTENT_REQUIRED,
                        'min_length': MSG_CONTENT_SHORT,
                        'max_length': MSG_CONTENT_LONG})

    class Meta:
        model = Post
        fields = ('content', )


class NewThreadForm(forms.Form):
    """Form to start a new thread."""
    title = StrippedCharField(min_length=5, max_length=255,
                              label=_lazy(u'Title:'),
                              widget=forms.TextInput(attrs={'size': 80}),
                              error_messages={'required': MSG_TITLE_REQUIRED,
                                              'min_length': MSG_TITLE_SHORT,
                                              'max_length': MSG_TITLE_LONG})
    content = StrippedCharField(
        label=_lazy(u'Content:'),
        min_length=5,
        max_length=10000,
        widget=forms.Textarea(attrs={'rows': 30, 'cols': 76}),
        error_messages={'required': MSG_CONTENT_REQUIRED,
                        'min_length': MSG_CONTENT_SHORT,
                        'max_length': MSG_CONTENT_LONG})


class EditThreadForm(forms.ModelForm):
    """Form to start a new thread."""
    title = StrippedCharField(min_length=5, max_length=255,
                              label=_lazy(u'Title:'),
                              widget=forms.TextInput(attrs={'size': 80}),
                              error_messages={'required': MSG_TITLE_REQUIRED,
                                              'min_length': MSG_TITLE_SHORT,
                                              'max_length': MSG_TITLE_LONG})

    class Meta:
        model = Thread
        fields = ('title',)


class EditPostForm(forms.Form):
    """Form to edit an existing post."""
    content = StrippedCharField(
        label=_lazy(u'Content:'),
        min_length=5,
        max_length=10000,
        widget=forms.Textarea(attrs={'rows': 30, 'cols': 76}),
        error_messages={'required': MSG_CONTENT_REQUIRED,
                        'min_length': MSG_CONTENT_SHORT,
                        'max_length': MSG_CONTENT_LONG})

    class Meta:
        model = Post
        exclude = ('thread', 'author', 'updated', 'created', 'updated_by')

kitsune/kbforums/templates/kbforums/base.html
{% extends "base.html" %}
{% from "wiki/includes/sidebar_modules.html" import document_tools with context %}
{% from 'includes/common_macros.html' import for_contributors_sidebar %}
{% if not styles %}
  {% set styles = ('forums',) %}
{% endif %}
{% if not scripts %}
  {% set scripts = ('forums',) %}
{% endif %}
{% set meta = (('robots', 'noindex'),) %}

{% block side_top %}
  {% block side_top_top %}{% endblock %}
  {% if document %}
    {{ document_tools(document, document.parent, user, 'discussion', settings) }}
  {% else %}
  	{{ for_contributors_sidebar(user, settings.WIKI_DEFAULT_LANGUAGE, active='article-discussions') }}
  {% endif %}
  {% if user.is_authenticated() %}
    <div id="doc-watch">
      {% include "kbforums/includes/watch_locale.html" %}
    </div>
  {% endif %}
{% endblock %}

kitsune/kbforums/templates/kbforums/confirm_post_delete.html
{% extends "kbforums/base.html" %}
{% from "kbforums/includes/macros.html" import kbforums_warning with context %}
{# L10n: {t} is the title of the thread. {d} is the name of the document. #}
{% set title = _('Delete Post | {t} | {d} Discussion | Knowledge Base')|f(t=thread.title, d=document.title) %}
{% set crumbs = [(document.get_absolute_url(), document.title),
                 (url('wiki.discuss.threads', document.slug), _('Discuss')),
                 (url('wiki.discuss.posts', document.slug, thread.id), thread.title),
                 (None, _('Delete Post'))] %}

{% block content %}
<div class="grid_9">
<article id="confirm-delete" class="main">
  {{ kbforums_warning(document, user) }}
  <h1>{{ _('Are you sure you want to delete this post?') }}</h1>
  <div class="post-to-delete">
    <label>{{ _('Author') }}</label>
    <div>{{ display_name(post.creator) }}</div>
    <label>{{ _('Date') }}</label>
    <div>{{ datetimeformat(post.created, format='longdatetime') }}</div>
    <label>{{ _('Content') }}</label>
    <div class="content">{{ post.content_parsed }}</div>

    <form action="{{ url('wiki.discuss.delete_post', document.slug, thread.id, post.id) }}" method="post">
      {{ csrf() }}
      <p>
        {{ _('You are about to permanently delete this post. <strong>This cannot be undone!</strong> Are you sure you want to continue?')|safe }}
      </p>
      <input type="submit" value="{{ _('Delete') }}" />
      <a href="{{ url('wiki.discuss.posts', document.slug, thread.id) }}">{{ _('Cancel') }}</a>
    </form>
  </div>
</article>
</div>
{% endblock %}

kitsune/kbforums/templates/kbforums/confirm_thread_delete.html
{% extends "kbforums/base.html" %}
{% from "kbforums/includes/macros.html" import kbforums_warning with context %}
{# L10n: {t} is the title of the thread. {d} is the name of the document. #}
{% set title = _('Delete Thread | {t} | {d} Discussion | Knowledge Base')|f(t=thread.title, d=document.title) %}
{% set crumbs = [(document.get_absolute_url(), document.title),
                 (url('wiki.discuss.threads', document.slug), _('Discuss')),
                 (url('wiki.discuss.posts', document.slug, thread.id), thread.title),
                 (None, _('Delete Thread'))] %}

{% block content %}
<div class="grid_9">
<article id="confirm-delete" class="main">
  {{ kbforums_warning(document, user) }}
  <h1>{{ _('Are you sure you want to delete this thread?') }}</h1>
  <div class="thread-to-delete">
    <label>{{ _('Title') }}</label>
    <div class="content">{{ thread.title }}</div>
    <label>{{ _('Creator') }}</label>
    <div>{{ display_name(thread.creator) }}</div>
    <label>{{ _('Date') }}</label>
    <div>{{ datetimeformat(thread.created, format='longdatetime') }}</div>
    <label>{{ _('Number of Replies') }}</label>
    <div>{{ thread.replies }}</div>

    <form action="{{ url('wiki.discuss.delete_thread', document.slug, thread.id) }}" method="post">
      {{ csrf() }}
      <p>
        {{ _('You are about to permanently delete this thread. <strong>This cannot be undone!</strong> Are you sure you want to continue?')|safe }}
      </p>
      <input type="submit" value="{{ _('Delete') }}" />
      <a href="{{ url('wiki.discuss.posts', document.slug, thread.id) }}">{{ _('Cancel') }}</a>
    </form>
  </div>
</article>
</div>
{% endblock %}

kitsune/kbforums/templates/kbforums/edit_post.html
{% extends "kbforums/base.html" %}
{% from "layout/errorlist.html" import errorlist %}
{% from "includes/common_macros.html" import content_editor with context %}
{% from "kbforums/includes/macros.html" import kbforums_warning with context %}
{# L10n: {t} is the title of the thread. {d} is the name of the document. #}
{% set title = _('Edit a post | {t} | {d} Discussion | Knowledge Base')|f(t=thread.title, d=document.title) %}
{% set crumbs = [(document.get_absolute_url(), document.title),
                 (url('wiki.discuss.threads', document.slug), _('Discuss')),
                 (url('wiki.discuss.posts', document.slug, thread.id), thread.title),
                 (None, _('Edit a post'))] %}
{% set styles = ('forums', 'jqueryui') %}
{% set scripts = ('forums', 'jqueryui') %}

{% block content %}
  <article id="edit-post" class="grid_9">
    {{ kbforums_warning(document, user) }}
    <h1>{{ _('Edit a post') }}</h1>

    <form action="{{ url('wiki.discuss.edit_post', document.slug, thread.id, post.id) }}" method="post" class="edit-post">
      {{ csrf() }}
      {{ errorlist(form) }}

      <div class="form-widget{% if form.content.errors %} invalid{% endif %}">
        {{ form.content.label_tag()|safe }}
        <div class="content-box">
          {{ content_editor(form.content) }}
        </div>
      </div>

      <div class="form-widget submit">
        <button type="submit" class="btn btn-submit big">{{ _('Update post') }}</button>
        <button type="submit" id="preview" name="preview" class="btn"
            data-preview-url="{{ url('wiki.discuss.post_preview_async', document.slug) }}"
            data-preview-container-id="post-preview"
            data-preview-content-id="id_content">{{ _('Preview') }}
        </button>
        <a class="btn" href="{{ url('wiki.discuss.posts', document.slug, thread.id) }}">{{ _('Cancel') }}</a>
      </div>
    </form>

    <div id="post-preview">
      {% if post_preview %}
        {% include "kbforums/includes/post_preview.html" %}
      {% endif %}
    </div>
  </article>
{% endblock %}

kitsune/kbforums/templates/kbforums/new_thread.html
{% extends "kbforums/base.html" %}
{% from "layout/errorlist.html" import errorlist %}
{% from "includes/common_macros.html" import content_editor with context %}
{% from "kbforums/includes/macros.html" import kbforums_warning with context %}
{# L10n: {d} is the name of the document. #}
{% set title = _('Create a new thread | {d} | Knowledge Base')|f(d=document.title) %}
{% set crumbs = [(document.get_absolute_url(), document.title),
                 (url('wiki.discuss.threads', document.slug), _('Discuss')),
                 (None, _('Create a new thread'))] %}
{% set styles = ('forums', 'jqueryui') %}
{% set scripts = ('forums', 'jqueryui') %}

{% block content %}
  <article id="new-thread" class="grid_9">
    {{ kbforums_warning(document, user) }}
    <h1>{{ _('Create a new thread') }}</h1>

    {% if request.limited %}
      <div class="warning-box">
        {{ _('You have exceeded the number of threads and replies that can be posted in a given amount of time. Please try again shortly.') }}
      </div>
    {% endif %}

    <form action="{{ url('wiki.discuss.new_thread', document.slug) }}" method="post" class="new-thread">
      {{ csrf() }}
      {{ errorlist(form) }}

      {% for field in form %}
        <div class="form-widget{% if field.errors %} invalid{% endif %}">
          {{ field.label_tag()|safe }}
          {% if field.name == 'content' %}
            <div class="content-box">
              {{ content_editor(field) }}
            </div>
          {% else %}
            {{ field|safe }}
          {% endif %}
        </div>
      {% endfor %}

      <div class="form-widget submit">
        <button type="submit" class="btn btn-submit big">{{ _('Post Thread') }}</button>
        <button type="submit" class="btn" id="preview" name="preview"
            data-preview-url="{{ url('wiki.discuss.post_preview_async', document.slug) }}"
            data-preview-container-id="post-preview"
            data-preview-content-id="id_content">{{ _('Preview') }}
        </button>
        <a class="btn" href="{{ url('wiki.discuss.threads', document.slug) }}">{{ _('Cancel') }}</a>
      </div>

      <div id="post-preview">
        {% if post_preview %}
          {% include "kbforums/includes/post_preview.html" %}
        {% endif %}
      </div>
    </form>
  </article>
{% endblock %}

kitsune/kbforums/templates/kbforums/posts.html
{% extends "kbforums/base.html" %}
{% from "layout/errorlist.html" import errorlist %}
{% from "includes/common_macros.html" import content_editor with context %}
{% from "kbforums/includes/macros.html" import kbforums_warning with context %}
{# L10n: {t} is the title of the thread. {d} is the name of the document. #}
{% set title = _('{t} | {d} Discussion | Knowledge Base')|f(t=thread.title, d=document.title) %}
{% set crumbs = [(document.get_absolute_url(), document.title),
                 (url('wiki.discuss.threads', document.slug), _('Discuss')),
                 (None, thread.title)] %}
{% set styles = ('forums', 'jqueryui') %}
{% set scripts = ('forums', 'jqueryui') %}

{% block side_top_top %}
  <ul id="thread-actions" class="sidebar-nav">
    {% if perms.kbforums.change_thread or (thread.creator == request.user and not thread.is_locked) %}
      <li><a href="{{ url('wiki.discuss.edit_thread', document.slug, thread.id) }}">{{ _('Edit this thread') }}</a></li>
    {% endif %}
    {% if perms.kbforums.delete_thread %}
      <li><a href="{{ url('wiki.discuss.delete_thread', document.slug, thread.id) }}">{{ _('Delete this thread') }}</a></li>
    {% endif %}
    {% if perms.kbforums.lock_thread %}
      <li>
        <form  id="thread-lock-form" action="{{ url('wiki.discuss.lock_thread', document.slug, thread.id) }}" method="post">
          {{ csrf() }}
        </form>
        <a data-type="submit" data-form="thread-lock-form">{% if thread.is_locked %}{{ _('Unlock this thread') }}{% else %}{{ _('Lock this thread') }}{% endif %}</a>
      </li>
    {% endif %}
    {% if perms.kbforums.sticky_thread %}
      <li>
        <form id="thread-sticky-form" action="{{ url('wiki.discuss.sticky_thread', document.slug, thread.id) }}" method="post">
          {{ csrf() }}
        </form>
        <a data-type="submit" data-form="thread-sticky-form">{% if thread.is_sticky %}{{ _('Unsticky this thread') }}{% else %}{{ _('Sticky this thread') }}{% endif %}</a>
      </li>
    {% endif %}
  </ul>
{% endblock %}

{% block content %}
  <div class="grid_9">
    <article id="posts" class="main">
      {{ kbforums_warning(document, user) }}
      <h1>{{ thread.title }}</h1>
      <ul class="cf" id="thread-meta">
        {% if count %}<li>{{ count - 1 }} {{ _('Replies') }}</li>{% endif %}
        {% if last_post %}<li>{{ _('Last reply by') }} {{ display_name(last_post.creator) }}</li>{% endif %}
        {% if thread.is_sticky %}<li>{{ _('Sticky') }}</li>{% endif %}
        {% if thread.is_locked %}<li>{{ _('Locked') }}</li>{% endif %}
      </ul>
      {% if user.is_authenticated() %}
        <form action="{{ url('wiki.discuss.watch_thread', document.slug, thread.id) }}" method="post">
          {{ csrf() }}
          {% if is_watching_thread %}
            {% set watch = _('Stop watching this thread') %}
            <input type="hidden" name="watch" value="no" />
          {% else %}
            {% set watch = _('Watch this thread') %}
            <input type="hidden" name="watch" value="yes" />
          {% endif %}
          <button type="submit" title="{{ watch }}" class="btn" id="watch-thread-toggle"><img src="{{ STATIC_URL }}sumo/img/blank.png" alt="" /> {{ watch }}</button>
        </form>
      {% endif %}

      {% if posts %}
        <ol class="posts">
          {% for post in posts.object_list %}
            <li class="cf" id="post-{{ post.id }}">
              {% include "kbforums/includes/post.html" %}
            </li>
          {% endfor %}
        </ol>

        {{ posts|paginator }}

      {% else %}
        <p>{{ _('Oh, no! Looks like there are no posts!') }}</p>
      {% endif %}

      {% if user.is_authenticated() and not thread.is_locked %}
        <form id="post-a-reply" action="{{ url('wiki.discuss.reply', document.slug, thread.id)|urlparams(hash='post-a-reply') }}" method="post">
          {{ csrf() }}
          <h3 id="thread-reply-title">{{ _('Post a reply') }}</h3>
          {{ errorlist(form) }}

          {% if request.limited %}
            <div class="warning-box">
              {{ _('You have exceeded the number of threads and replies that can be posted in a given amount of time. Please try again shortly.') }}
            </div>
          {% endif %}

          <div id="thread-reply">
            {{ content_editor(form.content) }}
          </div>

          <div class="editor-actions">
            <button type="submit" class="btn btn-submit big">{{ _('Post Reply') }}</button>
            <button type="submit" class="btn" id="preview" name="preview"
                data-preview-url="{{ url('wiki.discuss.post_preview_async', document.slug) }}"
                data-preview-container-id="post-preview"
                data-preview-content-id="id_content">{{ _('Preview Reply') }}
            </button>
          </div>
        </form>
      {% elif user.is_authenticated() and thread.is_locked %}
        <div id="thread-reply">
          <p id="thread-locked">{{ _('This thread has been locked. It is no longer possible to post new replies.') }}</p>
        </div>
      {% endif %}
      <div id="post-preview">
        {% if post_preview %}
          {% include "kbforums/includes/post_preview.html" %}
        {% endif %}
      </div>
    </article>
  </div>
{% endblock %}